spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://hotdeal-database.cu9sxsoss0ar.ap-northeast-2.rds.amazonaws.com:3306/hotdeal?serverTimezone=UTC&characterEncoding=UTF-8
        username: admin
        password: gktelf18!!
    slave1:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://hotdeal-read-database-1.cu9sxsoss0ar.ap-northeast-2.rds.amazonaws.com:3306/hotdeal?serverTimezone=UTC&characterEncoding=UTF-8
        username: admin
        password: gktelf18!!
    slave2:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://hotdeal-read-database-2.cu9sxsoss0ar.ap-northeast-2.rds.amazonaws.com:3306/hotdeal?serverTimezone=UTC&characterEncoding=UTF-8
        username: admin
        password: gktelf18!!



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false