# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    ## 1) git ignore에 등록된 application.properties 파일 생성해주기

    ## 2) 스프링 프로젝트 jar 파일 빌드
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    ## 3) Docker Hub에 이미지 push 하기
    - name: Docker build
      run: |
#        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker login -u ${{ secrets.DOCKER_USERNAME }}
        !Joyanggi7052
        docker build -t hotdeal-cicd .
        docker tag hotdeal-cicd jyg8033/hotdeal-cicd:${GITHUB_SHA::7}
        docker push jyg8033/hotdeal-cicd:${GITHUB_SHA::7}